// Generated by Wrangler on Thu Jul 18 2024 09:59:25 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	SERVICE_NAME: "htmx-board-game";
	BASELIME_API_KEY: string;
	GAME_STATE: DurableObjectNamespace;
}
