name = "htmx-hono-board-game"
compatibility_date = "2024-07-01"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"


[[durable_objects.bindings]]
name = "GAME_STATE"
class_name = "GameState"
#
#[[durable_objects.bindings]]
#name = "CARD_GAME"
#class_name = "CardGame"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["GameState"]
